### ISSUE TITLE
[1.14.4] Please update to forge .45 for breaking changes, the mod no longer works.

### ISSUE THREAD

**Issue by ProsperCraft** [bl4ckscor3/ChanceGlobe#5]
https://twitter.com/LexManos/status/1158426171500924930?s=09

**Comment by bl4ckscor3** [comment]
I don't use any of the affected events in this mod. Did you even test it with that Forge version? I don't have any issues with it.
Should there be something I missed, please open a new issue with the crash report/log and I'll see what I can do.

**Comment by ProsperCraft** [comment]
I tested mods one at a time for 20 hours and yours was one that caused the issue. Crash logs are worthless in this case. See - https://www.minecraftforge.net/forum/topic/74421-1144-forge-28045-mods-randomly-not-loading-properly/

**Comment by bl4ckscor3** [comment]
Sorry, but I don't see how my mod is causing issues. Chance Globe is not affected by the changes in Forge 28.0.45, as it doesn't make use of any of the events that got moved. The other changes in that Forge version are not breaking changes, and only affect how Forge behaves regardless of which mods are installed.
The mod works fine when it is installed by itself, so it must be a Forge issue caused by some change in version 28.0.45, or a mod conflict (highly unlikely as Chance Globe doesn't do anything funny that could break other mods).

**Comment by ProsperCraft** [comment]
You are correct, I tried now again after a few hours sleep and a clean working pack of 130 mods and it loaded fine, my test environment must have got dirty.
